services:
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=store_db
    volumes:
      - postgres-data:/bitnami/postgresql
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/store_db?schema=public
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local